version: '3.8'
services:
  test-database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5436:5432"
    volumes:
      - test-db-data:/var/lib/postgresql/data
    networks:
      - test-network

volumes:
  test-db-data:
networks:
  test-network:
    driver: bridge