version: '3.8'
services:
  database:
    container_name: "wms-db"
    image: postgres:16-alpine
    restart: always
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - wms-api
    healthcheck:
      test: "CMD-SHELL pg_isready -d $$POSTGRES_DB"
      interval: 1s
      timeout: 5s
      retries: 10

  api:
    container_name: "wms-api"
    depends_on:
      - database
    links:
      - database
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - '3001:3001'
    networks:
      - wms-api
      - aseca-environment
      
volumes:
  db-data:

networks:
  wms-api:
    name: wms-api
    driver: bridge
  aseca-environment:
    external: true